name: ImageOnMap
main: fr.moribus.imageonmap.ImageOnMap
version: "5.0.0"
api-version: "1.13"


commands:
  tomap:
    description: Render an image in a map
    usage: /<command> [URL]
  maptool:
    description: Manage maps
  maps:
    description: Manage maps through a GUI
  givemap:
    description: Give a map to a player from a playerMapStore, by default take from the player that make the command
    usage: /<command> [player_from] player_to map_name
  placemap:
    description: Place a map remotely and deploy it
    usage: /<command> [player_from]:<map_name> <N/S/E/W> <UP/DOWN/WALL> x y z

permissions:
  imageonmap.*:
    description: "Grants all the user permissions (excluding administrative ones)."
    default: true
    children:
      imageonmap.userender: true
      imageonmap.new: true
      imageonmap.list: true
      imageonmap.listother: false
      imageonmap.get: true
      imageonmap.getother: false
      imageonmap.explore: true
      imageonmap.exploreother: false
      imageonmap.rename: true
      imageonmap.placesplattermap: true
      imageonmap.removesplattermap: true
      imageonmap.delete: true
      imageonmap.deleteother: false
      imageonmap.bypasssize: false
      imageonmap.give: false
      imageonmap.update: true
      imageonmap.updateother: false
      imageonmap.bypassmaplimit: false
      imageonmap.bypassimagelimit: false
      imageonmap.bypasswhitelist: true
      imageonmap.placeinvisiblesplattermap: true
      imageonmap.remoteplacing: false

  imageonmap.userender:
    description: "Allows you to use /tomap and related commands (/maptool getremaining). Alias of imageonmap.new."
    default: true

  imageonmap.new:
    description: "Allows you to use /tomap and related commands (/maptool getremaining)."
    default: true

  imageonmap.list:
    description: "Allows you to list the images you rendered."
    default: true

  imageonmap.listother:
    description: "Allows you to list the images a player have rendered."
    default: op

  imageonmap.get:
    description: "Allows you to get a new map among the ones you already rendered, and related commands (/maptool getremaining)."
    default: true

  imageonmap.getother:
    description: "Allows you to get a new map among the ones a player have already rendered."
    default: op

  imageonmap.explore:
    description: "Allows you to open a GUI with all your maps."
    default: true

  imageonmap.exploreother:
    description: "Allows you to open a GUI with all of the player maps."
    default: op

  imageonmap.rename:
    description: "Allows you to rename a map you rendered in the past."
    default: true

  imageonmap.delete:
    description: "Allows you to delete a map you rendered in the past."
    default: true

  imageonmap.give:
    description: "Allows you to give a map to a specified player."
    default: op

  imageonmap.deleteother:
    description: "Allows you to delete a map a player rendered in the past."
    default: op

  imageonmap.placesplattermap:
    description: "Allows you to place a splatter map."
    default: true

  imageonmap.removesplattermap:
    description: "Allows you to remove a splatter map from a wall by sneaking and breaking a map."
    default: true

  imageonmap.administrative:
    description: "Allows you to perform administrative tasks (like /maptool migrate)."
    default: op

  imageonmap.bypasssize:
    description: "Allows you to create maps larger than the configured limit."
    default: op

  imageonmap.update:
    description: "Allows you to update an existing map with a new image."
    default: true

  imageonmap.updateother:
    description: "Allows you to update an existing map of an other player with a new image."
    default: op

  imageonmap.bypassmaplimit:
    description: "Allows you to bypass permission node check for the number of used map (by default users have an unlimited amount of maps)."
    default: op

  imageonmap.bypassimagelimit:
    description: "Allows you to bypass permission node check for the number of images in the playerMapStore (by default users have an unlimited amount of images)."
    default: op

  imageonmap.bypasswhitelist:
    description: "Allows you to ignore the restriction on the allow list for image hosting website."
    default: true

  imageonmap.placeinvisiblesplattermap:
    description: "Allows you to make the item frame on which you placed your splatter map invisible."
    default: true

  imageonmap.remoteplacing:
    description: "Allows you to remotly place a map from a playerMapStore to a specific position."
    default: op